#include <bits/stdc++.h>
using namespace std;
static const int M=420;
using BS=bitset<M>;
long long vp(long long n,int p){long long e=0;while(n%p==0){n/=p;e++;}return e;}
long long pwll(long long a,int e){long long r=1;while(e--)r*=a;return r;}
long long modpow(long long a,long long e,int p){long long r=1%p;a%=p;while(e){if(e&1)r=r*a%p;a=a*a%p;e>>=1;}return r;}
long long invmod(long long a,int p){a%=p;if(a<0)a+=p;return modpow(a,p-2,p);}
int ord10(int p){long long x=1;for(int n=1;n<p;n++){x=x*10%p;if(x==1)return n;}return 0;}
struct PM{int p,o;vector<BS> masks;double density;};
struct Combo{int z,w,g;};
long long C0of(int w){return 1LL*w*(10*w-1);}
int cg(int g){int c=1;while(g%(c*2)==0)c*=2;while(g%(c*5)==0)c*=5;return c;}
long long stableR(int z,int w,int g,long long N,long long mod){__int128 zw=1LL*z*w;__int128 v=(zw*zw+(__int128)2*g*(1-10LL*w)*((__int128)(N-1)*(N-1)+zw*zw))%mod;long long r=(long long)v;if(r<0)r+=mod;return r;}
vector<char> squareTable(int mod){vector<char>s(mod);for(int x=0;x<mod;x++)s[1LL*x*x%mod]=1;return s;}
pair<vector<char>,bool> allowedVal(int z,int w,int g,int p,int depth){int mod=1;for(int i=0;i<depth;i++)mod*=p;auto sq=squareTable(mod);vector<char>ok(depth,0);for(int n=1;n<mod;n++)if(sq[stableR(z,w,g,n,mod)]){int e=0,x=n;while(x%p==0){x/=p;e++;}if(e<depth)ok[e]=1;}bool tail=sq[stableR(z,w,g,0,mod)];return{ok,tail};}
vector<int> unitClasses(int w,int g,int a,int b){int c=cg(g),r=g/c;long long C0=C0of(w);int vc=vp(C0,2);vector<int>out;int e2=2+vc+a;if(e2%2||b%2)return out;for(int m=1;m<40;m++)if(gcd(m,10)==1){long long u2=-(C0>>vc)*r;u2%=8;if(u2<0)u2+=8;u2=u2*modpow(5,b,8)%8;u2=u2*(m%8)%8;long long u5=(-4LL*(C0%5)*(r%5))%5;if(u5<0)u5+=5;u5=u5*modpow(2,a,5)%5;u5=u5*(m%5)%5;if(u2==1&&(u5==1||u5==4))out.push_back(m);}return out;}
PM buildmask(int z,int w,int gamma,int p){int o=ord10(p),c=cg(gamma),r=gamma/c;long long C0=C0of(w),U0=10LL*c*gamma*(20*w-1);auto sq=squareTable(p);vector<BS>masks(p);long long cinv=invmod(c,p);for(int kr=0;kr<o;kr++){long long T=modpow(10,kr,p),L=T*cinv%p;BS kb;for(int kk=kr;kk<M;kk+=o)kb.set(kk);for(int N=0;N<p;N++){long long b1=(10*T%p*T-w)%p;if(b1<0)b1+=p;long long a2=(10*T%p*T-z)%p;if(a2<0)a2+=p;long long Q=(100*T%p*T-10*w+1)%p;if(Q<0)Q+=p;long long a1=(100*T%p*T%p*T+(10*(5-z-w)+1LL)*T+N-1)%p;if(a1<0)a1+=p;long long C=(10*T%p*T%p*a1+a2)%p;long long NN=(a1*a1+(a2*b1%p)*(a2*b1%p))%p;long long D=T*Q%p;long long K=(b1*b1%p*C%p*C-D*D%p*NN)%p;if(K<0)K+=p;long long BB=(1LL*N*T-gamma)%p;if(BB<0)BB+=p;long long RR=(K-2*BB%p*Q%p*NN)%p;if(RR<0)RR+=p;if(!sq[RR])continue;long long A0=1000LL%p*modpow(c,4,p)%p*(1LL*r*r%p)%p;long long C1=10LL%p*(1LL*c*c%p)%p*(1LL*r*r%p)%p*((20LL*w-1)%p)%p;long long base=(C0%p*N%p*N-(U0%p)*L%p*N+A0*L%p*L+(r%p)*(U0%p)-C1)%p;if(base<0)base+=p;long long coef=(r-L*N)%p;if(coef<0)coef+=p;if(coef){int tr=(int)((p-base)%p*invmod(coef,p)%p);masks[tr]|=kb;}else if(base==0){for(int tr=0;tr<p;tr++)masks[tr]|=kb;}}}long long bits=0;for(auto&b:masks)bits+=b.count();return{p,o,move(masks),double(bits)/(double(p)*M)};}
pair<vector<int>,int> goodResidues(int z,int w,int gamma,long long t,int p){int o=ord10(p),c=cg(gamma),r=gamma/c;long long C0=C0of(w),U0=10LL*c*gamma*(20*w-1),U=U0+t;auto sq=squareTable(p);vector<int>good;long long cinv=invmod(c,p);for(int kr=0;kr<o;kr++){long long T=modpow(10,kr,p),L=T*cinv%p;for(int N=0;N<p;N++){long long A0=1000LL%p*modpow(c,4,p)%p*(1LL*r*r%p)%p;long long cc=(A0*L%p*L+(r%p)*(U%p)-10LL%p*(1LL*c*c%p)%p*(1LL*r*r%p)%p*((20LL*w-1)%p))%p;if(cc<0)cc+=p;long long ff=(C0%p*N%p*N-(U%p)*L%p*N+cc)%p;if(ff<0)ff+=p;if(ff)continue;long long b1=(10*T%p*T-w)%p;if(b1<0)b1+=p;long long a2=(10*T%p*T-z)%p;if(a2<0)a2+=p;long long Q=(100*T%p*T-10*w+1)%p;if(Q<0)Q+=p;long long a1=(100*T%p*T%p*T+(10*(5-z-w)+1LL)*T+N-1)%p;if(a1<0)a1+=p;long long C=(10*T%p*T%p*a1+a2)%p;long long NN=(a1*a1+(a2*b1%p)*(a2*b1%p))%p;long long D=T*Q%p;long long K=(b1*b1%p*C%p*C-D*D%p*NN)%p;if(K<0)K+=p;long long BB=(1LL*N*T-gamma)%p;if(BB<0)BB+=p;long long RR=(K-2*BB%p*Q%p*NN)%p;if(RR<0)RR+=p;if(sq[RR]){good.push_back(kr);break;}}}return{good,o};}
bool compatible(const BS&mask,const vector<int>&g,int o){int gg=gcd(M,o);for(int a=0;a<M;a++)if(mask.test(a))for(int b:g)if((a-b)%gg==0)return true;return false;}
int main(){vector<Combo>combos={{1,1,32},{1,1,34},{1,1,36},{1,1,38},{1,3,24},{1,3,26},{1,3,28},{1,3,30},{1,3,32},{1,3,34},{1,3,36},{1,3,38},{3,1,22},{3,1,24},{3,1,26},{3,1,28},{3,1,30},{3,1,32},{3,1,34},{3,1,36},{3,1,38},{1,2,30},{1,2,32},{1,2,38},{3,2,22},{3,2,30},{3,2,32},{3,2,38},{1,4,24},{1,4,26}};vector<int>common={3,7,11,13,29,31,37,41,43,61,71,101,127,211,239,241,271,281,421,1933,2161,2689,3541,4649};vector<int>tailored={17,19,73,89,113,137,251,337,1009,4201};unsigned long long grand=0,grandCommon=0,grandFinal=0;for(auto cb:combos){int z=cb.z,w=cb.w,g=cb.g,c=cg(g),r=g/c;long long C0=C0of(w),U0=10LL*c*g*(20*w-1);long long lower=c*(C0+1000LL*g*g);long double upper=(long double)c*((long double)C0/10.0L+10000.0L*g*g)+1.0L;long long Umin=lower+1,Umax=(long long)ceill(upper)-1;if(z==3&&w==1&&g==22)Umin=max<long long>(Umin,3867967);long long lo=Umin-U0,hi=Umax-U0;auto[ok2,tail2]=allowedVal(z,w,g,2,12);auto[ok5,tail5]=allowedVal(z,w,g,5,6);int vc=vp(C0,2);vector<PM>pms;for(int p:common)pms.push_back(buildmask(z,w,g,p));sort(pms.begin(),pms.end(),[](auto&a,auto&b){return a.density<b.density;});vector<pair<long long,BS>>commonSurv;unsigned long long total=0;int maxa=0;while((1LL<<(maxa+1))<=hi&&maxa<60)maxa++;int maxb=0;while(pwll(5,maxb+1)<=hi)maxb++;for(int a=0;a<=maxa;a++){if(a<vc||(a-vc)%2)continue;int n2=(a-vc)/2;if(w%2==0&&n2<1)continue;if(!((n2<12&&ok2[n2])||(n2>=12&&tail2)))continue;for(int b=0;b<=maxb;b++){if(b%2)continue;int n5=b/2;if(!((n5<6&&ok5[n5])||(n5>=6&&tail5)))continue;auto cls=unitClasses(w,g,a,b);if(cls.empty())continue;__int128 scale=(__int128)pwll(2,a)*pwll(5,b);if(scale>hi)continue;__int128 mod=40*scale;for(int mr:cls){__int128 base=scale*mr;__int128 q;if(base>=lo)q=0;else q=((__int128)lo-base+mod-1)/mod;for(__int128 tt=base+q*mod;tt<=hi;tt+=mod){long long t=(long long)tt;total++;BS mask;mask.set();for(auto&pm:pms){mask&=pm.masks[t%pm.p];if(mask.none())break;}if(mask.any())commonSurv.push_back({t,mask});}}}}unsigned long long final=0;for(auto&tm:commonSurv){bool alive=true;for(int p:tailored){auto[gg,o]=goodResidues(z,w,g,tm.first,p);if(!compatible(tm.second,gg,o)){alive=false;break;}}if(alive){final++;cerr<<"FINAL SURV "<<z<<","<<w<<","<<g<<" t="<<tm.first<<"\n";}}grand+=total;grandCommon+=commonSurv.size();grandFinal+=final;cout<<"("<<z<<","<<w<<","<<g<<") local="<<total<<" common="<<commonSurv.size()<<" final="<<final<<"\n";}cout<<"TOTAL local="<<grand<<" common="<<grandCommon<<" final="<<grandFinal<<"\n";if(grand!=93580902ULL||grandCommon!=33ULL||grandFinal!=0ULL)return 1;cout<<"CERTIFICATE OK: all k>=26 central denominator states are empty.\n";return 0;}
