#!/usr/bin/env python3
"""Certificate for external-shared-outer-nogo.md.

A descendant-common prime is also an additive prime, so the rational-root
coefficient ratio is locked to R0(K,zeta).  If the same non-3 inert prime pays
both outer cofactors Xi_- and Xi_+, then Phi(2)=Phi(4)=0.

For a genuine external prime the actual root J0=3-C/D is not 2,3,4.  Exact
quartic division therefore forces J0=2K-2*zeta-9, hence
    C/D = 12 + 2*zeta - 2*K.
The descendant defect reader differs from this by
    63*K^2 / (16*(2*K-9)).
Thus, in the noncentral K-unit sector, p=7.  The full F_7 outer system has only
(K,zeta)=(3,-3), which has C/D=0 and is a target boundary.

The only K=0 coefficient boundary is p=11491.  Its unique shared-outer zeta is
743.  A complete audit of the two genuine sphere branches gives six algebraic
decimal phases, none in the subgroup generated by 10; hence tau=10^{-M} cannot
occur.
"""

import sympy as sp

K, zeta, J = sp.symbols("K zeta J")
R0 = K**2 - (18 + 4*zeta)*K + 18*zeta + 55
Phi = sp.expand(
    J*(J + 2*zeta)*(K - J)**2 - R0*(J + zeta)**2
)
Phi2 = sp.expand(Phi.subs(J, 2))
Phi4 = sp.expand(Phi.subs(J, 4))

# Exact division by the two outer evaluation points.
Q, Rem = sp.div(sp.Poly(Phi, J), sp.Poly((J-2)*(J-4), J))
assert sp.factor(Q.as_expr()) == (J-3)*(J-2*K+2*zeta+9)
assert sp.expand(
    2*Rem.as_expr() - ((4-J)*Phi2 + (J-2)*Phi4)
) == 0

# Hence Phi2=Phi4=0 gives four roots 2,3,4 and J*=2K-2zeta-9.
delta_outer = 12 + 2*zeta - 2*K
Jstar = 2*K - 2*zeta - 9
assert sp.expand(3 - Jstar - delta_outer) == 0

# Universal descendant defect reader in the noncentral sector.
delta_desc = delta_outer + sp.Rational(63, 16)*K**2/(2*K-9)
assert sp.factor((delta_desc-delta_outer)*16*(2*K-9)) == 63*K**2

# The central elimination factor is spurious for non-3 odd primes: at K=9/2
# the two outer equations differ by the nonzero constant 48.
p2c = sp.factor(Phi2.subs(K, sp.Rational(9, 2)))
p4c = sp.factor(Phi4.subs(K, sp.Rational(9, 2)))
assert sp.simplify(p4c-p2c) == 48

# K-unit generic sector: p|63 leaves only p=7 among non-3 inert primes.
assert sp.factorint(63) == {3: 2, 7: 1}
assert 7 % 4 == 3

# Full shared-outer F_7 audit.  The only state is target-boundary C/D=0.
shared7 = []
for k in range(7):
    for zz in range(7):
        if int(Phi2.subs({K:k, zeta:zz})) % 7 == 0 and int(Phi4.subs({K:k, zeta:zz})) % 7 == 0:
            shared7.append((k, zz, int(delta_outer.subs({K:k, zeta:zz})) % 7))
assert shared7 == [(3, 4, 0)]

# K=0 coefficient boundary.  The exact zeta resultant leaves one non-3 inert
# prime, 11491, and its shared root is unique.
P20 = sp.Poly(Phi2.subs(K, 0), zeta)
P40 = sp.Poly(Phi4.subs(K, 0), zeta)
res0 = abs(int(sp.resultant(P20.as_expr(), P40.as_expr(), zeta)))
assert sp.factorint(res0) == {2: 10, 3: 6, 11491: 1}
p = 11491
assert sp.isprime(p) and p % 4 == 3
G0 = sp.gcd(sp.Poly(P20, modulus=p), sp.Poly(P40, modulus=p)).monic()
assert G0 == sp.Poly(zeta - 743, zeta, modulus=p)
zeta0 = 743

# ---------------------------------------------------------------------------
# Fixed-11491 pure-spontaneous sphere/decimal audit.
# At K=s/tau=0 one has s=9+y=0, hence y=-9.  The two explicit sphere roots
# z_i(x,y) are those certified in spontaneous-sphere-roots.md.  Since
# zeta=z_i/tau, tau=z_i/zeta0.  The compact branch quadratic becomes
# c=(55+18*zeta0)*tau^2.  Enumerate its genuine F_p roots exactly.
# ---------------------------------------------------------------------------
y = (-9) % p

def inv(a):
    return pow(a % p, -1, p)

def branch_data(x, which):
    d = (225*x*x - y) % p
    y2 = y*y % p
    asp = (4*d*d - x*y2*(99*x-4)) % p
    aminus = (asp - 2*y2*(x+2)*(x+2)) % p
    aplus = (202500*pow(x,4,p) + 99*x*x*y2 - 4*x*y2 - 4*y2) % p
    delta0 = (2025*x*x - 18*y - y2) % p
    G = (
        410062500*pow(x,6,p)
        - 407025*pow(x,4,p)*y2
        - 7290000*pow(x,4,p)*y
        - 8100*pow(x,3,p)*y2
        + 99*x*x*pow(y,4,p)
        + 3600*x*x*pow(y,3,p)
        + 24300*x*x*y2
        - 4*x*pow(y,4,p)
        - 4*pow(y,4,p)
    ) % p
    den = 400*x*x*pow(y,3,p)*(x+2)*(x+2) % p
    if den == 0:
        return None
    if which == 1:
        zb = (-aplus*asp*inv(den)) % p
    else:
        if delta0 == 0:
            return None
        zb = asp*G*inv(den)*inv(delta0) % p
    c = (x+2)*(x+2)*(2025*x*x+y2)*inv(100*x*x) % p
    return zb, c, d, asp, aminus, delta0

coef = (55 + 18*zeta0) % p
states = []
for x in range(1, p):
    if (x+2) % p == 0:
        continue
    for which in (1, 2):
        data = branch_data(x, which)
        if data is None:
            continue
        zb, c, d, asp, aminus, delta0 = data
        if zb == 0:
            continue
        tau = zb*inv(zeta0) % p
        if (c - coef*tau*tau) % p == 0:
            # All listed branch-boundary factors are genuine units.
            assert all(v % p for v in (x, x+2, y, d, asp, aminus, delta0))
            states.append((which, x, zb, tau))

assert states == [
    (1, 241, 11030, 4902),
    (2, 241, 461, 6589),
    (1, 4766, 2557, 653),
    (2, 4766, 8934, 10838),
    (1, 8871, 6488, 4169),
    (2, 8871, 5003, 7322),
]

# Any true decimal phase tau=10^{-M} belongs to <10>.  It is enough to use
# 10^766=1; none of the six algebraic phases satisfies the same relation.
assert pow(10, 766, p) == 1
for _which, _x, _zb, tau in states:
    assert pow(tau, 766, p) != 1

print("OK: genuine A2 external descendant-common prime cannot pay both outer cofactors")
