#!/usr/bin/env python3
"""Exact certificate for spontaneous-source-singular-decimal-orbit.md."""

import sympy as sp

p = 1746991
tau0 = 807263

assert sp.isprime(p)
ord10 = sp.n_order(10, p)
assert ord10 == 174699
assert sp.factorint(ord10) == {3:2, 7:1, 47:1, 59:1}
assert p - 1 == 10*ord10

# Every actual tau=10^(-M) lies in <10>, hence satisfies tau^ord10=1.
assert pow(10, ord10, p) == 1

# The unique projected singular tau is outside that subgroup.
assert pow(tau0, ord10, p) == 119562
assert pow(tau0, ord10, p) != 1

# Equivalently its inverse is not generated by 10 either.
target = pow(tau0, -1, p)
assert pow(target, ord10, p) != 1

print("OK: A2 source singular tau is outside the decimal orbit")
