#!/usr/bin/env python3
"""Mechanical audit for the DD circular-decimal hard-source lock.

The script checks:
1. the exact discrete circular-interval bound;
2. bidirectional m2 folding on toy moduli;
3. invariance of the corrected hard p-depth under decimal shifting;
4. the universal 7/8 consequence used by the failure continuation.

It is only an algebra/combinatorics audit.  It does not certify DD emptiness by
finite computation.
"""

from __future__ import annotations

from math import floor


def circular_distance(e: int, m: int) -> int:
    q = e // m
    return min(abs(e - q * m), abs(e - (q + 1) * m))


def r_circ(m: int, d: int, c10: int, s10: int) -> int:
    return min(circular_distance(d + t, m) for t in range(-s10, c10 + 1))


def check_interval_bound() -> None:
    for m in range(1, 28):
        for d in range(0, 4 * m + 7):
            for c10 in range(0, 2 * m + 2):
                for s10 in range(0, 2 * m + 2):
                    r = r_circ(m, d, c10, s10)
                    bound = max(0, floor((m - c10 - s10) / 2))
                    assert r <= bound
                    assert r <= m // 2
                    if c10 + s10 >= m - 1:
                        assert r == 0


def check_bidirectional_folding() -> None:
    # C_Q = u1*10^m + u2 = 3*10^2+7 = 307.
    modulus = 307
    u1, u2, m = 3, 7, 2
    assert (u1 * 10**m + u2) % modulus == 0

    # Start from A*10^E = B mod C_Q for arbitrary positive/negative E
    # interpreted in the unit group.  Reduce to the nearest circular exponent
    # and check the concrete integer congruence generated by the proof.
    A = 11
    for E in range(-9, 10):
        inv10 = pow(10, -1, modulus)
        if E >= 0:
            B = A * pow(10, E, modulus) % modulus
        else:
            B = A * pow(inv10, -E, modulus) % modulus

        q, r = divmod(E, m)
        if q >= 0:
            left_coeff = A * (-u2) ** q
            right_coeff = B * u1**q
        else:
            ell = -q
            left_coeff = A * u1**ell
            right_coeff = B * (-u2) ** ell
        assert (left_coeff * 10**r - right_coeff) % modulus == 0

        if r > m / 2:
            # A'10^r=B' -> (B'u1)10^(m-r)=-A'u2.
            assert (
                right_coeff * u1 * 10 ** (m - r) + left_coeff * u2
            ) % modulus == 0


def check_hard_depth_invariance() -> None:
    # Sweep abstract corrected hard ledgers.
    for E in range(0, 6):
        for j in range(0, 6):
            M = max(E, j)
            for t in range(0, 5):
                for n0 in range(0, 5):
                    alpha = t + max(E - j, 0)
                    right_baseline = j + alpha
                    assert right_baseline == M + t
                    left_baseline = M + t
                    assert left_baseline == right_baseline

                    for h in range(1, 8):
                        c = h + 2 * t + n0 + M + j
                        residual = c - (M + t)
                        assert residual == h + t + n0 + j
                        assert residual > 0


def check_failure_constant() -> None:
    # r_circ <= m2/2 <= S/2 gives
    # f >= S-r_circ/4 >= 7S/8 asymptotically.
    for S in range(2, 100):
        for m2 in range(1, S + 1):
            rmax = m2 / 2
            lower = S - rmax / 4
            assert lower >= 7 * S / 8


def main() -> None:
    check_interval_bound()
    check_bidirectional_folding()
    check_hard_depth_invariance()
    check_failure_constant()
    print("DD circular decimal-phase hard-source checks passed")


if __name__ == "__main__":
    main()
