#!/usr/bin/env python3
"""Finite valuation sanity checks for full-v2 projective polarization.

This script only checks the local valuation pattern used in
`dd-corrected-v2-projective-polarization-2026-09-06.md` on explicit toy
integer-sphere data.  It is not a proof of the asymptotic theorem.
"""

from math import gcd


def v_p(n: int, p: int) -> int:
    e = 0
    while n % p == 0:
        n //= p
        e += 1
    return e


def local_pattern() -> None:
    # p=5, h=1.  Choose a primitive 3-4-5 sphere with the pair-max role
    # on y2,y3 after multiplying y1,H by p:
    # 15^2 + 4^2 + 12^2 = 385 is not square, so use a Pythagorean
    # quadruple generated by y1=5, y2=12, y3=84, H=85:
    # 25+144+7056=7225=85^2.
    p = 5
    h = 1
    y1, y2, y3, H = 5, 12, 84, 85

    assert y1 * y1 + y2 * y2 + y3 * y3 == H * H
    assert v_p(y1, p) >= h
    assert v_p(H, p) >= h
    assert v_p(y2, p) == 0
    assert v_p(y3, p) == 0
    assert v_p(y2 * y2 + y3 * y3, p) >= 2 * h
    assert gcd(p, H + y3) == 1
    assert gcd(p, y1 * y1 + y2 * y2) == 1


def projective_denominator() -> None:
    p = 5
    y1, y2, y3, H = 5, 12, 84, 85
    g12 = gcd(y1, y2)
    z0 = (H + y3) // gcd(g12, H + y3)
    assert z0 == 169
    assert gcd(p, z0) == 1


def main() -> None:
    local_pattern()
    projective_denominator()
    print("DD full-v2 projective polarization sanity check passed")


if __name__ == "__main__":
    main()
